# Generated by Django 6.0.3 on 2026-03-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_type', models.CharField(choices=[('t2.micro', 't2.micro - 1 vCPU, 1GB RAM'), ('t2.small', 't2.small - 1 vCPU, 2GB RAM'), ('t2.medium', 't2.medium - 2 vCPU, 4GB RAM'), ('t2.large', 't2.large - 2 vCPU, 8GB RAM'), ('t2.xlarge', 't2.xlarge - 4 vCPU, 16GB RAM'), ('t2.2xlarge', 't2.2xlarge - 8 vCPU, 32GB RAM'), ('t3.micro', 't3.micro - 2 vCPU, 1GB RAM'), ('t3.small', 't3.small - 2 vCPU, 2GB RAM'), ('t3.medium', 't3.medium - 2 vCPU, 4GB RAM'), ('t3.large', 't3.large - 2 vCPU, 8GB RAM'), ('t3.xlarge', 't3.xlarge - 4 vCPU, 16GB RAM'), ('t3.2xlarge', 't3.2xlarge - 8 vCPU, 32GB RAM')], max_length=50)),
                ('count', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
