# Generated by Django 6.0.2 on 2026-04-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=256)),
                ('date', models.DateField(db_index=True)),
                ('price_krw', models.FloatField()),
                ('source', models.CharField(default='csv', max_length=64)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item_id', 'date'), name='uniq_dashboard_agriactual_item_date')],
            },
        ),
        migrations.CreateModel(
            name='AgriPredictBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=256)),
                ('origin_date', models.DateField()),
                ('horizon', models.PositiveSmallIntegerField(default=10)),
                ('points', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item_id', '-created_at'], name='dashboard_a_item_id_b623ba_idx')],
            },
        ),
    ]
