# Generated by Django 6.0.2 on 2026-04-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_agriactual_agripredictbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('kamis', 'KAMIS 농산물 가격'), ('opinet', '오피넷 유가'), ('kma', '기상청 일자료')], db_index=True, max_length=16)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('item_key', models.CharField(default='default', max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source', '-snapshot_date'], name='dashboard_a_source_d2935b_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'snapshot_date', 'item_key'), name='uniq_dashboard_apisnapshot_src_date_item')],
            },
        ),
    ]
