# Generated by Django 6.0.2 on 2026-04-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_apisnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisnapshot',
            name='source',
            field=models.CharField(choices=[('kamis', 'KAMIS 농산물 가격'), ('opinet', '오피넷 유가'), ('kma', '기상청 일자료'), ('nongnet', '농넷 가락시장 경락가격')], db_index=True, max_length=16),
        ),
    ]
