"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-16z&vb6$#rwe$vcy0k(b_tzambcjykapgypm0fw4(*tm!fyvct'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,13.124.13.133").split(",")
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# --- 농업 예측 / Firebase / OpenAI ---
AGRI_TRAIN_CSV = BASE_DIR / "residual" / "production_split" / "production_split" / "train_data.csv"
AGRI_TEST_CSV = BASE_DIR / "residual" / "production_split" / "production_split" / "test_data.csv"
AGRI_CONTEXT_DAYS = int(os.environ.get("AGRI_CONTEXT_DAYS", "365"))
AGRI_FORECAST_DAYS = int(os.environ.get("AGRI_FORECAST_DAYS", "10"))
AGRI_FINAL_HANDOFF_API_URL = (
    os.environ.get("AGRI_FINAL_HANDOFF_API_URL", "").strip()
    or "http://13.124.13.133"
).rstrip("/")
AGRI_FINAL_HANDOFF_TIMEOUT = int(os.environ.get("AGRI_FINAL_HANDOFF_TIMEOUT", "300"))
AGRI_USE_FINAL_HANDOFF_API = os.environ.get("AGRI_USE_FINAL_HANDOFF_API", "1").lower() in (
    "1",
    "true",
    "yes",
)
# 외부 실제가격 API (선택). 비어 있으면 CSV에서 해당 일자 조회
AGRIDATA_API_URL = os.environ.get("AGRIDATA_API_URL", "").strip()
AGRIDATA_API_KEY = os.environ.get("AGRIDATA_API_KEY", "").strip()
# GPT 설명용 뉴스·요약 텍스트(선택). UTF-8 파일 경로 — 비우면 기상 위주만 사용
AGRI_NEWS_CONTEXT_PATH = os.environ.get("AGRI_NEWS_CONTEXT_PATH", "").strip()

FIREBASE_CREDENTIALS_PATH = os.environ.get("FIREBASE_CREDENTIALS_PATH", "").strip()
USE_FIRESTORE = bool(
    FIREBASE_CREDENTIALS_PATH and os.path.isfile(FIREBASE_CREDENTIALS_PATH)
)

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "").strip()
OPENAI_EXPLAIN_MODEL = os.environ.get("OPENAI_EXPLAIN_MODEL", "gpt-4o-mini")
OPENAI_NEWS_MODEL = os.environ.get("OPENAI_NEWS_MODEL", "gpt-4o-mini")

# Chronos 추론 스킵(개발용 더미 예측)
CHRONOS_SKIP_INFERENCE = os.environ.get("CHRONOS_SKIP_INFERENCE", "").lower() in (
    "1",
    "true",
    "yes",
)

# --- 외부 자동 수집 API ---
# 기상청 공공데이터포털 인증키(URL-encoded일 수도 있음)
WEATHER_API_KEY = os.environ.get("WEATHER_API", "").strip()
WEATHER_STN_IDS = os.environ.get("WEATHER_STN_IDS", "108").strip() or "108"
# 오피넷 무료 API 키
OPINET_API_KEY = os.environ.get("OPINET_API", "").strip()
# KAMIS 농산물 가격 정보 서비스
KAMIS_API_KEY = os.environ.get("KAMIS_API_KEY", "").strip()
KAMIS_API_ID = os.environ.get("KAMIS_API_ID", "").strip() or "tester"

# 자동 외부 데이터 수집 스케줄러(Asia/Seoul 매일 00:00)
AGRI_AUTO_FETCH_ENABLED = os.environ.get(
    "AGRI_AUTO_FETCH_ENABLED", "true"
).lower() not in ("0", "false", "no")
